<script type="text/javascript" src="{{asset('/assets/js/jquery/jquery-3.7.0.min.js')}}"></script>
<script type="text/javascript" src="{{asset('/assets/js/jquery/jquery-ui.js')}}"></script>
<script type="text/javascript" src="{{asset('/assets/js/bootstrap/bootstrap.bundle.min.js')}}"></script>
<script type="text/javascript" src="{{asset('/assets/js/fontawesome/js/all.js')}}"></script>
<script type="text/javascript" src="{{asset('/assets/js/jquery/jquery.validationEngine.js')}}"></script>
<script type="text/javascript" src="{{asset('/assets/js/languages/jquery.validationEngine-es.js')}}"></script>
<script type="text/javascript" src="{{asset('/assets/js/datatables/jquery.dataTables.min.js')}}"></script>
<script type="text/javascript" src="{{asset('/assets/js/datatables/datatables.min.js')}}"></script>
<script type="text/javascript" src="{{asset('/assets/js/select2/select2.min.js')}}"></script>
<script type="text/javascript" src="{{asset('/assets/js/sweetalert2/sweetalert2.all.min.js')}}"></script>
<script type="text/javascript" src="{{asset('/assets/js/scripts/enlace.js')}}"></script>
<script type="text/javascript" src="{{asset('/assets/js/scripts/validaciones.js')}}"></script>
<script type="text/javascript" src="{{asset('/assets/js/scripts/frame.js')}}"></script>
<script type="text/javascript" src="{{asset('/assets/js/scripts/categorias.js')}}"></script>